services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development  # Enables auto-reloading
      - FLASK_APP=main.py  # Specifies the entry point file
    restart: always